#include "runtime/node_bootstrap_scripts.h"

namespace gode::node_bootstrap_scripts {

std::string commonjs_bootstrap_script() {
	return "const Module = require('module');"
		   "const path = require('path');"
		   "const fs = require('fs');"
		   "const gode = process._linkedBinding('godot');"
		   "const isGodotPath = p => typeof p === 'string' && (p.startsWith('res://') || p.startsWith('user://'));"
		   "const isGodeInternalCommonJSPath = p => typeof p === 'string' && ("
		   "  p === 'res://addons/gode/runtime/typescript_compiler.js' ||"
		   "  p === 'res://addons/gode/tsc/lib/typescript.js'"
		   ");"
		   "const isRes = p => typeof p === 'string' && p.startsWith('res://');"
		   "const isUser = p => typeof p === 'string' && p.startsWith('user://');"
		   "const toPosix = p => {"
		   "    if (isRes(p)) return '/__gode_res__/' + p.substring(6);"
		   "    if (isUser(p)) return '/__gode_user__/' + p.substring(7);"
		   "    return p;"
		   "};"
		   "const fromPosix = p => {"
		   "    if (p === '/__gode_res__' || p === '/__gode_res__/') return 'res://';"
		   "    if (p === '/__gode_user__' || p === '/__gode_user__/') return 'user://';"
		   "    if (p.startsWith('/__gode_res__/')) return 'res://' + p.substring(14);"
		   "    if (p.startsWith('/__gode_user__/')) return 'user://' + p.substring(15);"
		   "    return p;"
		   "};"
		   "const tryExtensions = (p) => {"
		   "    const exts = ['.js', '.json', '.node', '.mjs', '.cjs'];"
		   "    for (const ext of exts) {"
		   "        if (fs.existsSync(p + ext)) return p + ext;"
		   "    }"
		   "    return null;"
		   "};"
		   "const resolveAsFileOrDirectory = (p) => {"
		   "    if (fs.existsSync(p) && fs.statSync(p).isFile()) return p;"
		   "    const withExt = tryExtensions(p);"
		   "    if (withExt) return withExt;"
		   "    if (fs.existsSync(p) && fs.statSync(p).isDirectory()) {"
		   "        const pkgPath = path.join(p, 'package.json');"
		   "        if (fs.existsSync(pkgPath)) {"
		   "            try {"
		   "                const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));"
		   "                if (pkg.main) {"
		   "                    const main = path.resolve(p, pkg.main);"
		   "                    if (fs.existsSync(main) && fs.statSync(main).isFile()) return main;"
		   "                    const mainExt = tryExtensions(main);"
		   "                    if (mainExt) return mainExt;"
		   "                    const mainIndex = path.join(main, 'index.js');"
		   "                    if (fs.existsSync(mainIndex)) return mainIndex;"
		   "                }"
		   "            } catch(e){}"
		   "        }"
		   "        const index = path.join(p, 'index.js');"
		   "        if (fs.existsSync(index)) return index;"
		   "    }"
		   "    return null;"
		   "};"
		   "const packageSpecifierParts = (req) => {"
		   "    const parts = String(req || '').split('/');"
		   "    if (!parts[0]) return null;"
		   "    const pkgName = parts[0].startsWith('@') ? parts[0] + '/' + parts[1] : parts[0];"
		   "    if (parts[0].startsWith('@') && !parts[1]) return null;"
		   "    const subPath = parts.slice(pkgName.split('/').length).join('/');"
		   "    return { pkgName, subPath };"
		   "};"
		   "const packageExportTarget = (value, subpath, conditions) => {"
		   "    if (value === undefined || value === null) return null;"
		   "    if (typeof value === 'string') return subpath === '.' ? value : null;"
		   "    if (Array.isArray(value)) {"
		   "        for (const entry of value) { const target = packageExportTarget(entry, subpath, conditions); if (target) return target; }"
		   "        return null;"
		   "    }"
		   "    if (typeof value !== 'object') return null;"
		   "    const keys = Object.keys(value);"
		   "    const hasSubpathKeys = keys.some((key) => key === '.' || key.startsWith('./'));"
		   "    if (hasSubpathKeys) {"
		   "        if (Object.prototype.hasOwnProperty.call(value, subpath)) return packageExportTarget(value[subpath], '.', conditions);"
		   "        for (const key of keys) {"
		   "            const starIndex = key.indexOf('*');"
		   "            if (starIndex < 0) continue;"
		   "            const prefix = key.slice(0, starIndex);"
		   "            const suffix = key.slice(starIndex + 1);"
		   "            if (!subpath.startsWith(prefix) || !subpath.endsWith(suffix)) continue;"
		   "            const replacement = subpath.slice(prefix.length, subpath.length - suffix.length);"
		   "            const target = packageExportTarget(value[key], '.', conditions);"
		   "            if (target) return target.includes('*') ? target.split('*').join(replacement) : target;"
		   "        }"
		   "        return null;"
		   "    }"
		   "    for (const key of keys) {"
		   "        if (!conditions.has(key)) continue;"
		   "        const target = packageExportTarget(value[key], '.', conditions);"
		   "        if (target) return target;"
		   "    }"
		   "    return null;"
		   "};"
		   "const packageTargetPath = (pkgDir, target, requireDotSlash = true) => {"
		   "    if (typeof target !== 'string') return null;"
		   "    let relativeTarget = '';"
		   "    if (target.startsWith('./')) relativeTarget = target.slice(2);"
		   "    else if (!requireDotSlash && !target.startsWith('../') && !target.startsWith('/') && !target.includes('://')) relativeTarget = target;"
		   "    else return null;"
		   "    const resolved = path.resolve(pkgDir, relativeTarget);"
		   "    const normalized = resolved.replace(/\\\\/g, '/');"
		   "    const normalizedPkgDir = pkgDir.replace(/\\\\/g, '/').replace(/\\/+$/, '');"
		   "    if (normalized !== normalizedPkgDir && !normalized.startsWith(normalizedPkgDir + '/')) return null;"
		   "    return resolved;"
		   "};"
		   "const packageTargetEntry = (pkgDir, target, requireDotSlash = true) => {"
		   "    const resolved = packageTargetPath(pkgDir, target, requireDotSlash);"
		   "    return resolved ? resolveAsFileOrDirectory(resolved) : null;"
		   "};"
		   "const packageManifestEntry = (pkgDir, pkg, subPath) => {"
		   "    const exportSubpath = subPath ? './' + subPath : '.';"
		   "    if (pkg.exports !== undefined) {"
		   "        const target = packageExportTarget(pkg.exports, exportSubpath, new Set(['node', 'require', 'default']));"
		   "        return target ? packageTargetEntry(pkgDir, target) : null;"
		   "    }"
		   "    if (subPath) return resolveAsFileOrDirectory(path.join(pkgDir, subPath));"
		   "    return packageTargetEntry(pkgDir, pkg.main || './index.js', false);"
		   "};"
		   "const findInGodotPath = (base, req) => {"
		   "    const parts = packageSpecifierParts(req);"
		   "    if (parts) {"
		   "        const pkgDir = path.join(base, parts.pkgName);"
		   "        if (fs.existsSync(pkgDir)) {"
		   "            const pkgPath = path.join(pkgDir, 'package.json');"
		   "            if (fs.existsSync(pkgPath)) {"
		   "                try {"
		   "                    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));"
		   "                    const resolved = packageManifestEntry(pkgDir, pkg, parts.subPath);"
		   "                    if (resolved) return resolved;"
		   "                    if (pkg.exports !== undefined) return null;"
		   "                } catch(e){}"
		   "            }"
		   "        }"
		   "    }"
		   "    return resolveAsFileOrDirectory(path.join(base, req));"
		   "};"
		   "try {"
		   "  const _gode_module = new Module('godot');"
		   "  _gode_module.id = 'godot';"
		   "  _gode_module.exports = gode;"
		   "  _gode_module.loaded = true;"
		   "  _gode_module.filename = 'godot';"
		   "  Module._cache['godot'] = _gode_module;"
		   "} catch (e) {"
		   "  console.error('[Gode] Injection error:', e);"
		   "}"
		   ""
		   "globalThis.__gode_open_inspector = function(port, host, wait, autoIncrementPort, maxPortRetries) {"
		   "  const inspector = require('inspector');"
		   "  const startPort = Number.isInteger(port) && port >= 0 && port <= 65535 ? port : 9229;"
		   "  const safeHost = typeof host === 'string' && host.length > 0 ? host : '127.0.0.1';"
		   "  const attempts = autoIncrementPort ? Math.max(1, Number(maxPortRetries) || 20) : 1;"
		   "  let lastError = null;"
		   "  for (let i = 0; i < attempts; i++) {"
		   "    const candidate = startPort === 0 ? 0 : startPort + i;"
		   "    if (candidate > 65535) break;"
		   "    try {"
		   "      inspector.open(candidate, safeHost, false);"
		   "      const url = inspector.url() || '';"
		   "      let resolvedPort = candidate;"
		   "      try {"
		   "        const parsedUrl = new URL(url);"
		   "        if (parsedUrl.port) resolvedPort = Number(parsedUrl.port);"
		   "      } catch (e) {}"
		   "      globalThis.__gode_inspector_url = url;"
		   "      return { ok: true, url, port: resolvedPort, error: '' };"
		   "    } catch (e) {"
		   "      lastError = e;"
		   "    }"
		   "  }"
		   "  const message = lastError && (lastError.stack || lastError.message) || 'Failed to open Node inspector';"
		   "  globalThis.__gode_inspector_error = message;"
		   "  return { ok: false, url: '', port: startPort, error: message };"
		   "};"
		   ""
		   "globalThis.__gode_wait_for_debugger = function() {"
		   "  try {"
		   "    require('inspector').waitForDebugger();"
		   "    return { ok: true, error: '' };"
		   "  } catch (e) {"
		   "    return { ok: false, error: e && (e.stack || e.message) || String(e) };"
		   "  }"
		   "};"
		   ""
		   "globalThis.__gode_close_inspector = function() {"
		   "  try {"
		   "    require('inspector').close();"
		   "    globalThis.__gode_inspector_url = '';"
		   "    return { ok: true, error: '' };"
		   "  } catch (e) {"
		   "    return { ok: false, error: e && (e.stack || e.message) || String(e) };"
		   "  }"
		   "};"
		   ""
		   "const originalReadFileSync = fs.readFileSync;"
		   "fs.readFileSync = function(p, options) {"
		   "  if (isGodotPath(p)) {"
		   "    const content = gode.fs_readFile(p);"
		   "    if (content !== null) return content;"
		   "  }"
		   "  return originalReadFileSync.call(fs, p, options);"
		   "};"
		   ""
		   "const originalExistsSync = fs.existsSync;"
		   "fs.existsSync = function(p) {"
		   "  if (isGodotPath(p)) {"
		   "    return gode.fs_stat(p) > 0;"
		   "  }"
		   "  return originalExistsSync ? originalExistsSync.call(fs, p) : false;"
		   "};"
		   ""
		   "const originalStatSync = fs.statSync;"
		   "fs.statSync = function(p, options) {"
		   "  if (isGodotPath(p)) {"
		   "    const type = gode.fs_stat(p);"
		   "    if (type > 0) {"
		   "      return {"
		   "        isDirectory: () => type === 2,"
		   "        isFile: () => type === 1,"
		   "        mtime: new Date(),"
		   "        size: 0"
		   "      };"
		   "    }"
		   "  }"
		   "  return originalStatSync.call(fs, p, options);"
		   "};"
		   ""
		   "const originalJoin = path.join;"
		   "const originalResolve = path.resolve;"
		   "const originalDirname = path.dirname;"
		   ""
		   "path.join = function(...args) {"
		   "  if (args.some(isGodotPath)) {"
		   "      const mapped = args.map(toPosix);"
		   "      return fromPosix(path.posix.join(...mapped));"
		   "  }"
		   "  return originalJoin.apply(path, args);"
		   "};"
		   ""
		   "path.resolve = function(...args) {"
		   "  if (args.some(isGodotPath)) {"
		   "      const mapped = args.map(toPosix);"
		   "      return fromPosix(path.posix.resolve(...mapped));"
		   "  }"
		   "  return originalResolve.apply(path, args);"
		   "};"
		   ""
		   "path.dirname = function(p) {"
		   "  if (isGodotPath(p)) {"
		   "      return fromPosix(path.posix.dirname(toPosix(p)));"
		   "  }"
		   "  return originalDirname.call(path, p);"
		   "};"
		   ""
		   "const originalNodeModulePaths = Module._nodeModulePaths;"
		   "Module._nodeModulePaths = function(from) {"
		   "    if (isGodotPath(from)) {"
		   "        const paths = [];"
		   "        let p = from;"
		   "        while (true) {"
		   "            paths.push(p + (p.endsWith('/') ? '' : '/') + 'node_modules');"
		   "            const parent = path.dirname(p);"
		   "            if (parent === p) break;"
		   "            if (p === 'res://' || p === 'user://') break;"
		   "            p = parent;"
		   "        }"
		   "        return paths;"
		   "    }"
		   "    return originalNodeModulePaths.call(Module, from);"
		   "};"
		   ""
		   "const originalFindPath = Module._findPath;"
		   "Module._findPath = function(request, paths, isMain) {"
		   "  if (isGodotPath(request)) {"
		   "      return request;"
		   "  }"
		   "  const godotPaths = paths.filter(isGodotPath);"
		   "  for (const base of godotPaths) {"
		   "      const found = findInGodotPath(base, request);"
		   "      if (found) return found;"
		   "  }"
		   "  return originalFindPath.call(Module, request, paths, isMain);"
		   "};"
		   ""
		   "const originalResolveFilename = Module._resolveFilename;"
		   "Module._resolveFilename = function(request, parent, isMain, options) {"
		   "  if (isGodotPath(request)) {"
		   "    return request;"
		   "  }"
		   "  if (parent && parent.filename && isGodotPath(parent.filename)) {"
		   "    if (request.startsWith('./') || request.startsWith('../')) {"
		   "      const parentDir = path.dirname(parent.filename);"
		   "      const base = path.resolve(parentDir, request);"
		   "      const found = resolveAsFileOrDirectory(base);"
		   "      return found || base;"
		   "    }"
		   "    try {"
		   "      return originalResolveFilename.call(Module, request, parent, isMain, options);"
		   "    } catch(e) {"
		   "      const found = findInGodotPath(path.join(path.dirname(parent.filename), 'node_modules'), request)"
		   "        || findInGodotPath('user://node_modules', request)"
		   "        || findInGodotPath('res://node_modules', request);"
		   "      if (found) return found;"
		   "      throw e;"
		   "    }"
		   "  }"
		   "  return originalResolveFilename.call(Module, request, parent, isMain, options);"
		   "};"
		   ""
		   "globalThis.__gode_compile = function(code, filename) {"
		   "  try {"
		   "    const m = new Module(filename, module);"
		   "    m.filename = filename;"
		   "    m.paths = Module._nodeModulePaths(path.dirname(filename));"
		   "    m._compile(code, filename);"
		   "    return m.exports;"
		   "  } catch (e) {"
		   "    console.error('Gode compile error:', e);"
		   "    return e;"
		   "  }"
		   "};"
		   "const originalRequire = Module.prototype.require;"
		   "Module.prototype.require = function(id) {"
		   "  if (id === 'godot') {"
		   "    return gode;"
		   "  }"
		   "  return originalRequire.call(this, id);"
		   "};"
		   "const originalGlobalRequire = globalThis.require || Module.createRequire(process.cwd());"
		   "globalThis.require = function(id) {"
		   ""
		   "  if (id === 'godot') {"
		   "    return gode;"
		   "  }"
		   "  return originalGlobalRequire.call(this, id);"
		   "};"
		   "if (originalGlobalRequire) Object.assign(globalThis.require, originalGlobalRequire);"
		   ""
		   "const originalJsExtension = Module._extensions['.js'];"
		   "Module._extensions['.js'] = function(mod, filename) {"
		   "  if (isGodeInternalCommonJSPath(filename)) {"
		   "    const source = fs.readFileSync(filename, 'utf8');"
		   "    return mod._compile(source, filename);"
		   "  }"
		   "  return originalJsExtension.call(this, mod, filename);"
		   "};"
		   ""
		   // Patch process.dlopen: native .node modules must be loaded from real OS paths.
		   // Passing res:// paths to LoadLibraryW can produce invalid addresses and crash N-API initialization.
		   // Before loading .node, append its directory to PATH so Windows can find sibling DLLs such as ggml-cuda.dll.
		   "const _originalDlopen = process.dlopen;"
		   "process.dlopen = function(mod, filename, flags) {"
		   "  let realPath = filename;"
		   "  if (typeof filename === 'string') {"
		   "    let p = filename;"
		   "    if (p.startsWith('file://')) { try { p = require('url').fileURLToPath(p); } catch(_) {} }" // file:// → OS path
		   "    if (p.startsWith('res://')) { p = require('path').join(process.cwd(), p.slice(6)); }"
		   "    if (p.startsWith('\\\\\\\\?\\\\')) p = p.slice(4);" // Strip the \\?\ prefix.
		   "    realPath = p;"
		   "  }"
		   "  if (typeof realPath === 'string' && realPath.endsWith('.node') && typeof gode.preload_dlls === 'function') {"
		   "    try { gode.preload_dlls(require('path').dirname(realPath)); } catch(_) {}"
		   "  }"
		   "  return _originalDlopen(mod, realPath, flags);"
		   "};"
		   ""
		   "if (gode.GodotObject && gode.GodotObject.prototype) {"
		   "  gode.GodotObject.prototype.to_signal = function(signal, { timeoutMs, abortSignal } = {}) {"
		   "    const obj = this;"
		   "    return new Promise((resolve, reject) => {"
		   "      let done = false;"
		   "      let timer = null;"
		   "      const cleanup = () => {"
		   "        if (timer) clearTimeout(timer);"
		   "        if (abortSignal) abortSignal.removeEventListener('abort', onAbort);"
		   "        try { obj.disconnect(signal, callback); } catch (_) {}"
		   "      };"
		   "      const callback = (...args) => {"
		   "        if (done) return;"
		   "        done = true;"
		   "        cleanup();"
		   "        resolve(args.length <= 1 ? args[0] : args);"
		   "      };"
		   "      const onAbort = () => {"
		   "        if (done) return;"
		   "        done = true;"
		   "        cleanup();"
		   "        reject(new Error('to_signal: aborted'));"
		   "      };"
		   "      try {"
		   "        obj.connect(signal, callback);"
		   "      } catch (e) {"
		   "        cleanup();"
		   "        return reject(e);"
		   "      }"
		   "      if (abortSignal) abortSignal.addEventListener('abort', onAbort, { once: true });"
		   "      if (typeof timeoutMs === 'number' && timeoutMs > 0) {"
		   "        timer = setTimeout(() => {"
		   "          if (done) return;"
		   "          done = true;"
		   "          cleanup();"
		   "          reject(new Error(`to_signal: timeout waiting for '${signal}'`));"
		   "        }, timeoutMs);"
		   "      }"
		   "    });"
		   "  };"
		   "}"
		   ";"
		   "(function() {"
		   "  try {"
		   "    const compilerPath = 'res://addons/gode/runtime/typescript_compiler.js';"
		   "    const compilerSource = fs.readFileSync(compilerPath, 'utf8');"
		   "    const compiled = globalThis.__gode_compile(compilerSource, compilerPath);"
		   "    if (compiled instanceof Error) throw compiled;"
		   "  } catch(e) {"
		   "    globalThis.__gode_typescript_compiler_boot_error = e && (e.stack || e.message) || String(e);"
		   "  }"
		   "})()"
		   // Patch child_process.fork: intercept testBindingBinary forks and simulate success in-process.
		   // This avoids launching a GodotEngine.exe child process on Windows just for addon compatibility probes.
		   ";"
		   "(function() {"
		   "  try {"
		   "    const cp = require('child_process');"
		   "    const _origFork = cp.fork;"
		   "    cp.fork = function(modulePath, args, options) {"
		   "      if (typeof modulePath === 'string' && modulePath.includes('testBindingBinary')) {"
		   "        const { EventEmitter } = require('events');"
		   "        const mock = new EventEmitter();"
		   "        mock.pid = 0; mock.exitCode = null; mock.killed = false;"
		   "        mock.stdout = null; mock.stderr = null;"
		   "        mock.kill = function() {};"
		   "        mock.send = function(msg) {"
		   "          const self = this;"
		   "          if (msg && msg.type === 'start') {"
		   "            process.nextTick(() => self.emit('message', { type: 'loaded' }));"
		   "          } else if (msg && msg.type === 'test') {"
		   "            process.nextTick(() => self.emit('message', { type: 'done' }));"
		   "          } else if (msg && msg.type === 'exit') {"
		   "            process.nextTick(() => { mock.exitCode = 0; self.emit('exit', 0, null); });"
		   "          }"
		   "          return true;"
		   "        };"
		   "        process.nextTick(() => mock.emit('message', { type: 'ready' }));"
		   "        return mock;"
		   "      }"
		   "      return _origFork.apply(cp, arguments);"
		   "    };"
		   "  } catch(e) {}"
		   "})();";
}

std::string esm_bootstrap_script() {
	return "(function() {"
		   "const vm = require('vm');"
		   "const fs = require('fs');"
		   "const path = require('path');"
		   ""
		   "global.__gode_esm_supported = (typeof vm.SourceTextModule !== 'undefined');"
		   ""
		   "global.__gode_esm_cache = new Map();" // filepath -> namespace (fully evaluated)
		   "global.__gode_esm_pending = new Map();" // filepath -> Promise<namespace>
		   "global.__gode_esm_pending_source = new Map();" // filepath -> source for pending Promise
		   "global.__gode_esm_load_tokens = new Map();" // filepath -> token for the newest load
		   "global.__gode_esm_mod_cache = new Map();" // filepath/specifier -> vm.Module (for linker)
		   "global.__gode_esm_source_cache = new Map();" // filepath -> last successfully evaluated source
		   "global.__gode_esm_generation = 0;"
		   ""
		   // __gode_resolve_to_module resolves a specifier to a vm.Module.
		   // For ESM files, only create and return SourceTextModule; do not call link().
		   // Node's [kLink] machinery recursively invokes this linker asynchronously,
		   // avoiding synchronous recursion and stack overflows.
		   // Convert res:// paths to file:// URLs for import.meta.url.
		   // fileURLToPath() only accepts file:// URLs, so virtual paths must be converted.
		   "const _gode_is_virtual_path = (p) => typeof p === 'string' && (p.startsWith('res://') || p.startsWith('user://'));"
		   "const _gode_strip_module_generation = (p) => typeof p === 'string' ? p.replace(/\\?gode_gen=\\d+$/, '') : p;"
		   "const _gode_module_cache_key = (p) => String(global.__gode_esm_generation) + ':' + p;"
		   "const _gode_module_identifier = (p) => p + '?gode_gen=' + String(global.__gode_esm_generation);"
		   "const _gode_source_fallback = (p) => {"
		   "  if (typeof p !== 'string') return p;"
		   "  const normalized = p.replace(/\\\\/g, '/');"
		   "  const exportPrefix = 'res://.gode/build/typescript/';"
		   "  if (normalized.startsWith(exportPrefix)) return 'res://' + normalized.slice(exportPrefix.length);"
		   "  const buildMarker = '/.gode/build/typescript/';"
		   "  const buildIndex = normalized.indexOf(buildMarker);"
		   "  if (buildIndex >= 0) return 'res://' + normalized.slice(buildIndex + buildMarker.length);"
		   "  return p;"
		   "};"
		   "const _gode_existing_or_source = (p) => {"
		   "  if (fs.existsSync(p)) return p;"
		   "  const fallback = _gode_source_fallback(p);"
		   "  return fallback !== p && fs.existsSync(fallback) ? fallback : p;"
		   "};"
		   "const _gode_virtual_to_file_url = (p) => {"
		   "  p = _gode_strip_module_generation(p);"
		   "  if (!p) return p;"
		   "  if (p.startsWith('file://')) return p;"
		   "  if (!p.startsWith('res://')) return require('url').pathToFileURL(p).href;"
		   "  const rel = p.slice(6);"
		   "  const abs = require('path').join(process.cwd(), rel).replace(/\\\\/g, '/');"
		   "  return require('url').pathToFileURL(abs).href;"
		   "};"
		   "const _gode_should_invalidate_require_cache = (p) => {"
		   "  if (typeof p !== 'string') return false;"
		   "  const normalized = p.replace(/\\\\/g, '/');"
		   "  return _gode_is_virtual_path(p) || normalized.includes('/.gode/build/typescript/');"
		   "};"
		   "global.__gode_invalidate_esm_module = function(filepath) {"
		   "  global.__gode_esm_cache.clear();"
		   "  global.__gode_esm_pending.clear();"
		   "  global.__gode_esm_pending_source.clear();"
		   "  global.__gode_esm_load_tokens.clear();"
		   "  global.__gode_esm_source_cache.clear();"
		   "  global.__gode_esm_mod_cache.clear();"
		   "  global.__gode_esm_generation++;"
		   "  for (const key of Object.keys(require.cache)) {"
		   "    if (_gode_should_invalidate_require_cache(key)) delete require.cache[key];"
		   "  }"
		   "};"
		   "global.__gode_forget_esm_module = function(filepath) {"
		   "  filepath = _gode_strip_module_generation(filepath);"
		   "  global.__gode_esm_cache.delete(filepath);"
		   "  global.__gode_esm_pending.delete(filepath);"
		   "  global.__gode_esm_pending_source.delete(filepath);"
		   "  global.__gode_esm_load_tokens.delete(filepath);"
		   "  global.__gode_esm_source_cache.delete(filepath);"
		   "  const moduleCacheSuffix = ':' + filepath;"
		   "  for (const key of Array.from(global.__gode_esm_mod_cache.keys())) {"
		   "    if (String(key).endsWith(moduleCacheSuffix)) global.__gode_esm_mod_cache.delete(key);"
		   "  }"
		   "  if (_gode_should_invalidate_require_cache(filepath)) delete require.cache[filepath];"
		   "};"
		   ""
		   // Manually resolve package entries under res://node_modules/ when require.resolve cannot handle res:// paths.
		   "function __gode_existing_file_or_directory_entry(base) {"
		   "  if (fs.existsSync(base) && fs.statSync(base).isFile()) return base;"
		   "  for (const ext of ['.js', '.mjs', '.cjs', '.json']) {"
		   "    if (fs.existsSync(base + ext) && fs.statSync(base + ext).isFile()) return base + ext;"
		   "  }"
		   "  if (fs.existsSync(base) && fs.statSync(base).isDirectory()) {"
		   "    for (const ext of ['.js', '.mjs', '.cjs', '.json']) {"
		   "      const indexPath = path.join(base, 'index' + ext);"
		   "      if (fs.existsSync(indexPath) && fs.statSync(indexPath).isFile()) return indexPath;"
		   "    }"
		   "  }"
		   "  return null;"
		   "}"
		   "function __gode_package_export_target(value, subpath) {"
		   "  if (value === undefined || value === null) return null;"
		   "  if (typeof value === 'string') return subpath === '.' ? value : null;"
		   "  if (Array.isArray(value)) {"
		   "    for (const entry of value) { const target = __gode_package_export_target(entry, subpath); if (target) return target; }"
		   "    return null;"
		   "  }"
		   "  if (typeof value !== 'object') return null;"
		   "  const keys = Object.keys(value);"
		   "  const hasSubpathKeys = keys.some((key) => key === '.' || key.startsWith('./'));"
		   "  if (hasSubpathKeys) {"
		   "    if (Object.prototype.hasOwnProperty.call(value, subpath)) return __gode_package_export_target(value[subpath], '.');"
		   "    for (const key of keys) {"
		   "      const starIndex = key.indexOf('*');"
		   "      if (starIndex < 0) continue;"
		   "      const prefix = key.slice(0, starIndex);"
		   "      const suffix = key.slice(starIndex + 1);"
		   "      if (!subpath.startsWith(prefix) || !subpath.endsWith(suffix)) continue;"
		   "      const replacement = subpath.slice(prefix.length, subpath.length - suffix.length);"
		   "      const target = __gode_package_export_target(value[key], '.');"
		   "      if (target) return target.includes('*') ? target.split('*').join(replacement) : target;"
		   "    }"
		   "    return null;"
		   "  }"
		   "  const activeConditions = new Set(['node', 'import', 'module', 'default']);"
		   "  for (const key of keys) {"
		   "    if (!activeConditions.has(key)) continue;"
		   "    const target = __gode_package_export_target(value[key], '.');"
		   "    if (target) return target;"
		   "  }"
		   "  return null;"
		   "}"
		   "function __gode_package_target_path(pkgDir, target, requireDotSlash = true) {"
		   "  if (typeof target !== 'string') return null;"
		   "  let relativeTarget = '';"
		   "  if (target.startsWith('./')) relativeTarget = target.slice(2);"
		   "  else if (!requireDotSlash && !target.startsWith('../') && !target.startsWith('/') && !target.includes('://')) relativeTarget = target;"
		   "  else return null;"
		   "  const resolved = path.resolve(pkgDir, relativeTarget);"
		   "  const normalized = resolved.replace(/\\\\/g, '/');"
		   "  const normalizedPkgDir = pkgDir.replace(/\\\\/g, '/').replace(/\\/+$/, '');"
		   "  if (normalized !== normalizedPkgDir && !normalized.startsWith(normalizedPkgDir + '/')) return null;"
		   "  return resolved;"
		   "}"
		   "function __gode_package_target_entry(pkgDir, target, requireDotSlash = true) {"
		   "  const resolved = __gode_package_target_path(pkgDir, target, requireDotSlash);"
		   "  return resolved ? __gode_existing_file_or_directory_entry(resolved) : null;"
		   "}"
		   "function __gode_package_manifest_entry(pkgDir, pkg, subpath) {"
		   "  const exportSubpath = subpath ? './' + subpath : '.';"
		   "  if (pkg.exports !== undefined) {"
		   "    const exportedTarget = __gode_package_export_target(pkg.exports, exportSubpath);"
		   "    return exportedTarget ? __gode_package_target_entry(pkgDir, exportedTarget) : null;"
		   "  }"
		   "  if (subpath) return __gode_existing_file_or_directory_entry(path.join(pkgDir, subpath));"
		   "  return __gode_package_target_entry(pkgDir, pkg.module || pkg.main || './index.js', false);"
		   "}"
		   "function __gode_resolve_in_res(specifier, referrerPath) {"
		   "  const parts = specifier.split('/');"
		   "  const pkgName = parts[0].startsWith('@') ? parts[0] + '/' + parts[1] : parts[0];"
		   "  const subPath = parts.slice(pkgName.split('/').length).join('/');"
		   "  let searchDirs = [];"
		   "  const addSearchDirs = (fromPath) => {"
		   "    let d = path.dirname(fromPath);"
		   "    while (true) {"
		   "      const nodeModulesDir = path.join(d, 'node_modules');"
		   "      if (!searchDirs.includes(nodeModulesDir)) searchDirs.push(nodeModulesDir);"
		   "      if (d === 'res://' || d === 'user://') break;"
		   "      const p = path.dirname(d); if (p === d) break; d = p;"
		   "    }"
		   "  };"
		   "  addSearchDirs(referrerPath);"
		   "  const sourceReferrerPath = _gode_source_fallback(referrerPath);"
		   "  if (sourceReferrerPath !== referrerPath) addSearchDirs(sourceReferrerPath);"
		   "  if (!searchDirs.includes('res://node_modules')) searchDirs.push('res://node_modules');"
		   "  for (const base of searchDirs) {"
		   "    const pkgDir = path.join(base, pkgName);"
		   "    if (!fs.existsSync(pkgDir)) continue;"
		   "    const pkgJsonPath = path.join(pkgDir, 'package.json');"
		   "    if (!fs.existsSync(pkgJsonPath)) { if (subPath) return __gode_existing_file_or_directory_entry(path.join(pkgDir, subPath)); continue; }"
		   "    let pkg; try { pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf8')); } catch(_) { continue; }"
		   "    const resolved = __gode_package_manifest_entry(pkgDir, pkg, subPath);"
		   "    if (resolved) return resolved;"
		   "    if (pkg.exports !== undefined) return null;"
		   "  }"
		   "  return null;"
		   "}"
		   ""
		   // Resolve #subpath entries from package.json imports.
		   "function __gode_package_import_target(importsValue, specifier) {"
		   "  if (!importsValue || typeof importsValue !== 'object') return null;"
		   "  if (Object.prototype.hasOwnProperty.call(importsValue, specifier)) return __gode_package_export_target(importsValue[specifier], '.');"
		   "  for (const key of Object.keys(importsValue)) {"
		   "    const starIndex = key.indexOf('*');"
		   "    if (starIndex < 0) continue;"
		   "    const prefix = key.slice(0, starIndex);"
		   "    const suffix = key.slice(starIndex + 1);"
		   "    if (!specifier.startsWith(prefix) || !specifier.endsWith(suffix)) continue;"
		   "    const replacement = specifier.slice(prefix.length, specifier.length - suffix.length);"
		   "    const target = __gode_package_export_target(importsValue[key], '.');"
		   "    if (target) return target.includes('*') ? target.split('*').join(replacement) : target;"
		   "  }"
		   "  return null;"
		   "}"
		   "function __gode_resolve_pkg_import(specifier, referrerPath) {"
		   "  const startDirs = [];"
		   "  const addStartDir = (p) => { const d = path.dirname(p); if (!startDirs.includes(d)) startDirs.push(d); };"
		   "  addStartDir(referrerPath);"
		   "  const sourceReferrerPath = _gode_source_fallback(referrerPath);"
		   "  if (sourceReferrerPath !== referrerPath) addStartDir(sourceReferrerPath);"
		   "  for (const startDir of startDirs) {"
		   "    let dir = startDir;"
		   "    while (true) {"
		   "      const pkgPath = path.join(dir, 'package.json');"
		   "      if (fs.existsSync(pkgPath)) {"
		   "        try {"
		   "          const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));"
		   "          const target = __gode_package_import_target(pkg.imports, specifier);"
		   "          if (target) {"
		   "            if (target.startsWith('./')) return __gode_package_target_entry(dir, target);"
		   "            if (!target.startsWith('../') && !target.startsWith('/') && !target.includes('://')) return __gode_resolve_in_res(target, referrerPath);"
		   "            return null;"
		   "          }"
		   "        } catch(_) {}"
		   "      }"
		   "      if (dir === 'res://' || dir === 'user://') break;"
		   "      const parent = path.dirname(dir);"
		   "      if (parent === dir) break;"
		   "      dir = parent;"
		   "    }"
		   "  }"
		   "  return null;"
		   "}"
		   ""
		   "global.__gode_resolve_to_module = function(specifier, referrerPath) {"
		   "  referrerPath = _gode_strip_module_generation(referrerPath);"
		   "  let resolvedPath;"
		   "  if (specifier.startsWith('#')) {"
		   "    const pkgImport = __gode_resolve_pkg_import(specifier, referrerPath);"
		   "    if (!pkgImport) throw new Error(`Cannot find module '${specifier}' from '${referrerPath}'`);"
		   "    resolvedPath = pkgImport;"
		   "  } else if (specifier.startsWith('./') || specifier.startsWith('../')) {"
		   "    const dir = path.dirname(referrerPath);"
		   "    resolvedPath = path.resolve(dir, specifier);"
		   "    if (!fs.existsSync(resolvedPath)) {"
		   "      for (const ext of ['.mjs', '.js', '.cjs', '.json']) {"
		   "        if (fs.existsSync(resolvedPath + ext)) { resolvedPath = resolvedPath + ext; break; }"
		   "      }"
		   "    }"
		   "    resolvedPath = _gode_existing_or_source(resolvedPath);"
		   "  } else if (_gode_is_virtual_path(specifier)) {"
		   "    resolvedPath = _gode_existing_or_source(specifier);"
		   "  } else if (path.isAbsolute(specifier)) {"
		   "    resolvedPath = _gode_existing_or_source(specifier);"
		   "  } else if (specifier.startsWith('file://')) {"
		   "    resolvedPath = _gode_existing_or_source(require('url').fileURLToPath(specifier));"
		   "  } else {"
		   "    let _cjsMod; try { _cjsMod = require(specifier); } catch(_) {}"
		   "    if (_cjsMod !== undefined) {"
		   "      const cjsCacheKey = _gode_module_cache_key(specifier);"
		   "      if (global.__gode_esm_mod_cache.has(cjsCacheKey)) return global.__gode_esm_mod_cache.get(cjsCacheKey);"
		   "      const exportNames = Object.keys(_cjsMod);"
		   "      const names = exportNames.includes('default') ? exportNames : ['default', ...exportNames];"
		   "      const synMod = new vm.SyntheticModule(names, function() {"
		   "        this.setExport('default', _cjsMod);"
		   "        for (const key of exportNames) { this.setExport(key, _cjsMod[key]); }"
		   "      }, { identifier: _gode_module_identifier(specifier) });"
		   "      synMod.evaluate();"
		   "      global.__gode_esm_mod_cache.set(cjsCacheKey, synMod);"
		   "      return synMod;"
		   "    }"
		   "    try {"
		   "      resolvedPath = require.resolve(specifier, { paths: [path.dirname(referrerPath)] });"
		   "    } catch(e) {"
		   "      resolvedPath = __gode_resolve_in_res(specifier, referrerPath);"
		   "      if (!resolvedPath) {"
		   "        console.error('[gode] resolve failed: ' + specifier + ' from ' + referrerPath);"
		   "        throw new Error(`Cannot find module '${specifier}' from '${referrerPath}'`);"
		   "      }"
		   "    }"
		   "  }"
		   "  let source;"
		   "  resolvedPath = _gode_existing_or_source(resolvedPath);"
		   "  try {"
		   "    source = fs.readFileSync(resolvedPath, 'utf8');"
		   "  } catch(e) {"
		   "    console.error('[gode] readFileSync failed: ' + resolvedPath + ' => ' + e.message);"
		   "    throw e;"
		   "  }"
		   "  let cacheKey = _gode_module_cache_key(resolvedPath);"
		   "  if (global.__gode_esm_mod_cache.has(cacheKey)) {"
		   "    if (global.__gode_esm_source_cache.get(resolvedPath) === source) {"
		   "      return global.__gode_esm_mod_cache.get(cacheKey);"
		   "    }"
		   "    global.__gode_forget_esm_module(resolvedPath);"
		   "    cacheKey = _gode_module_cache_key(resolvedPath);"
		   "  }"
		   "  const isESM = resolvedPath.endsWith('.mjs') ||"
		   "    (resolvedPath.endsWith('.js') && /^\\s*(import|export)\\s+/m.test(source));"
		   "  if (isESM) {"
		   "    let mod;"
		   "    try {"
		   "      mod = new vm.SourceTextModule(source, {"
		   "        identifier: _gode_module_identifier(resolvedPath),"
		   "        initializeImportMeta(meta) { meta.url = _gode_virtual_to_file_url(resolvedPath); },"
		   "        importModuleDynamically: async (spec, ref) => {"
		   "          return await global.__gode_import_module(spec, ref.identifier);"
		   "        }"
		   "      });"
		   "    } catch(e) {"
		   "      console.error('[gode] SourceTextModule parse error in ' + resolvedPath + ': ' + e.message);"
		   "      throw e;"
		   "    }"
		   "    global.__gode_esm_mod_cache.set(cacheKey, mod);"
		   "    global.__gode_esm_source_cache.set(resolvedPath, source);"
		   "    return mod;"
		   "  } else {"
		   "    try {"
		   "      const cjsModule = require(resolvedPath);"
		   "      const expNames = Object.keys(cjsModule);"
		   "      const allNames = expNames.includes('default') ? expNames : ['default', ...expNames];"
		   "      const synMod = new vm.SyntheticModule(allNames,"
		   "        function() {"
		   "          this.setExport('default', cjsModule);"
		   "          for (const key of expNames) { this.setExport(key, cjsModule[key]); }"
		   "        }, { identifier: _gode_module_identifier(resolvedPath) });"
		   "      synMod.evaluate();"
		   "      global.__gode_esm_mod_cache.set(cacheKey, synMod);"
		   "      return synMod;"
		   "    } catch(e) {"
		   "      console.error('[gode] CommonJS module load failed: ' + resolvedPath + ' => ' + e.message);"
		   "      throw e;"
		   "    }"
		   "  }"
		   "};"
		   ""
		   "global.__gode_import_module = async function(specifier, referrerPath) {"
		   "  const mod = global.__gode_resolve_to_module(specifier, referrerPath);"
		   "  try {"
		   "    if (mod.status === 'unlinked') {"
		   "      await mod.link((nestedSpecifier, referencingModule) => {"
		   "        return global.__gode_resolve_to_module(nestedSpecifier, referencingModule.identifier);"
		   "      });"
		   "    }"
		   "    if (mod.status === 'linked') {"
		   "      await mod.evaluate();"
		   "    }"
		   "    if (mod.status === 'errored') {"
		   "      throw mod.error || new Error('ESM module evaluation failed: ' + (mod.identifier || specifier));"
		   "    }"
		   "    return mod;"
		   "  } catch(e) {"
		   "    global.__gode_esm_mod_cache.clear();"
		   "    throw e;"
		   "  }"
		   "};"
		   ""
		   "global.__gode_load_esm = async function(filepath, source) {"
		   "  if (!global.__gode_esm_supported) {"
		   "    throw new Error('vm.SourceTextModule is not available');"
		   "  }"
		   "  if (global.__gode_esm_source_cache.has(filepath) && global.__gode_esm_source_cache.get(filepath) !== source) {"
		   "    global.__gode_forget_esm_module(filepath);"
		   "  }"
		   "  if (global.__gode_esm_cache.has(filepath)) { return global.__gode_esm_cache.get(filepath); }"
		   "  if (global.__gode_esm_pending.has(filepath)) {"
		   "    if (global.__gode_esm_pending_source.get(filepath) === source) { return global.__gode_esm_pending.get(filepath); }"
		   "    global.__gode_forget_esm_module(filepath);"
		   "  }"
		   "  const loadToken = {};"
		   "  global.__gode_esm_load_tokens.set(filepath, loadToken);"
		   "  const loadPromise = (async () => {"
		   "    const module = new vm.SourceTextModule(source, {"
		   "      identifier: _gode_module_identifier(filepath),"
		   "      initializeImportMeta(meta) { meta.url = _gode_virtual_to_file_url(filepath); },"
		   "      importModuleDynamically: async (specifier, referrer) => {"
		   "        return await global.__gode_import_module(specifier, referrer.identifier);"
		   "      }"
		   "    });"
		   "    global.__gode_esm_mod_cache.set(_gode_module_cache_key(filepath), module);"
		   "    try {"
		   "      await module.link((specifier, referencingModule) => {"
		   "        return global.__gode_resolve_to_module(specifier, referencingModule.identifier);"
		   "      });"
		   "    } catch(e) {"
		   "      console.error('[gode] link error in ' + filepath + ': ' + e.message);"
		   "      if (e.stack) console.error(e.stack);"
		   "      global.__gode_esm_mod_cache.clear();"
		   "      throw e;"
		   "    }"
		   "    try {"
		   "      await module.evaluate();"
		   "    } catch(e) {"
		   "      console.error('[gode] evaluate error in ' + filepath + ': ' + e.message);"
		   "      if (e.stack) console.error(e.stack);"
		   "      global.__gode_esm_mod_cache.clear();"
		   "      throw e;"
		   "    }"
		   "    const ns = module.namespace;"
		   "    if (global.__gode_esm_load_tokens.get(filepath) === loadToken) {"
		   "      global.__gode_esm_cache.set(filepath, ns);"
		   "      global.__gode_esm_source_cache.set(filepath, source);"
		   "    }"
		   "    return ns;"
		   "  })().finally(() => {"
		   "    if (global.__gode_esm_pending.get(filepath) === loadPromise) {"
		   "      global.__gode_esm_pending.delete(filepath);"
		   "      global.__gode_esm_pending_source.delete(filepath);"
		   "    }"
		   "  });"
		   "  global.__gode_esm_pending.set(filepath, loadPromise);"
		   "  global.__gode_esm_pending_source.set(filepath, source);"
		   "  return loadPromise;"
		   "};"
		   ""
		   "global.__gode_compile_esm = async function(code, filename) {"
		   "  try {"
		   "    global.__gode_forget_esm_module(filename);"
		   "    const ns = await global.__gode_load_esm(filename, code);"
		   "    return ns;"
		   "  } catch (e) {"
		   "    console.error('[gode] compile_esm FAILED: ' + filename + ' => ' + (e && e.message));"
		   "    if (e && e.stack) console.error(e.stack);"
		   "    return e;"
		   "  }"
		   "};"
		   "})();";
}

} // namespace gode::node_bootstrap_scripts
