name: Feature request
description: Suggest a Gode feature or improvement.
title: "[Feature]: "
body:
  - type: textarea
    id: use-case
    attributes:
      label: Use case
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: API or behavior
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
    validations:
      required: false
